#!/bin/bash
# This script needs to be run from the testsuite/mpi directory

# Customization for the HET cluster at the University of Colorado
makefile=Make_mpi
run="/usr/local/mpich2-1.4.1p1/bin/mpirun -np 2"

# Require user to specify both directory and target
if [ $# -lt 2 ]; then
  echo "Try these:"
  echo "./run_tests KS_nHYP_FA hmc"
  echo "./run_tests KS_nHYP_FA hmc_APBC"
  echo "./run_tests wilson_flow Wflow"
  echo "./run_tests ks_vacpol vacpol && rm -f ../*TEST"
  exit 0
fi

dir=$1
target=$2

# Compile
cd ../../$dir/
echo "Compiling su3_$target..."
if ! make -f $makefile su3_$target >& /dev/null ; then
  echo "ERROR: su3_$target compilation failed"
  make -f $makefile su3_$target
  exit
fi

# Run
cd ../testsuite/
rm -f mpi/$target.out
echo "Running su3_$target..."
$run ../$dir/su3_$target < in.$target > mpi/$target.out

# Check
cd mpi/
d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' $target.ref $target.out`"
if [ -n "$d" ] ; then   # Non-zero string length
  echo "$target.ref and $target.out differ:"
  echo "$d"
else
  echo "PASS: su3_$target reproduces reference output"
fi
exit
