#!/bin/bash
# This script needs to be run from the testsuite/mpi directory

# May need to be customized for different platforms
makefile=Make_mpi
run="mpirun -np 2"

# Require user to specify both directory and target
if [ $# -lt 2 ]; then
  echo "Try these:"
  echo "./run_tests KS_nHYP_FA hmc"
  echo "./run_tests KS_nHYP_FA hmc_APBC"
  echo "./run_tests flow flow Wflow"
  echo "./run_tests flow flow Sflow"
  echo "./run_tests ks_vacpol vacpol && rm -f ../*TEST"
  echo "./run_tests mcrg_blocking mcrg"
  echo "./run_tests S4b_params S4b"
  echo "./run_tests mode_number mode"
  echo "./run_tests mode_number mode_APBC"
  echo "./run_tests ks_spectrum spectrum"
  exit 0
fi

# Most targets only have one infile, with the same name as the target itself
dir=$1
target=$2
if [ $# -lt 3 ]; then
  infile=$2
else
  infile=$3
fi

# Compile
cd ../../$dir/
echo "Compiling su3_$target..."
if ! make -f $makefile su3_$target >& /dev/null ; then
  echo "ERROR: su3_$target compilation failed"
  make -f $makefile su3_$target
  exit
fi

# Run
cd ../testsuite/
rm -f mpi/$infile.out
echo "Running su3_$target..."
$run ../$dir/su3_$target < in.$infile > mpi/$infile.out

# Check
cd mpi/
d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' $infile.ref $infile.out`"
if [ -n "$d" ] ; then   # Non-zero string length
  echo "$infile.ref and $infile.out differ:"
  echo "$d"
else
  echo "PASS: su3_$target reproduces reference output"
fi
exit
