#!/bin/bash
# This script needs to be run from the testsuite/scalar directory

# Require user to specify both directory and target
if [ $# -lt 2 ]; then
  echo "Try these:"
  echo "./run_tests KS_nHYP_FA hmc"
  echo "./run_tests KS_nHYP_FA hmc_APBC"
  echo "./run_tests eig_KS_PRIMME eig"
  echo "./run_tests wilson_flow Wflow"
  echo "./run_tests ks_vacpol vacpol && rm -f ../*TEST"
  echo "./run_tests mcrg_blocking mcrg"
  echo "./run_tests S4b_params S4b"
  echo "./run_tests mode_number mode"
  echo "./run_tests mode_number mode_APBC"
  echo "./run_tests ks_spectrum spectrum"
  exit 0
fi

dir=$1
target=$2

# Compile
cd ../../$dir/
echo "Compiling su3_$target..."
if ! make -f Make_scalar su3_$target >& /dev/null ; then
  echo "ERROR: su3_$target compilation failed"
  make -f Make_scalar su3_$target
  exit
fi

# Run
cd ../testsuite/
rm -f scalar/$target.out
echo "Running su3_$target..."
../$dir/su3_$target < in.$target > scalar/$target.out

# Check
cd scalar/
d="`diff -I'Time' -I'time' -I'seconds' -I'secs' -I'^start' -I'^exit:' $target.ref $target.out`"
if [ -n "$d" ] ; then   # Non-zero string length
  echo "$target.ref and $target.out differ:"
  echo "$d"
else
  echo "PASS: su3_$target reproduces reference output"
fi
exit
